{{- range .Values.apprepository.initialRepos }}
apiVersion: kubeapps.com/v1alpha1
kind: AppRepository
metadata:
  name: {{ .name }}
  labels:
    app: {{ template "kubeapps.apprepository.fullname" $ }}
    chart: {{ template "kubeapps.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
annotations:
  helm.sh/hook: pre-install
spec:
  type: helm
  url: {{ .url }}
  {{- if or .caCert .authorizationHeader }}
  auth:
    {{- if .caCert }}
    customCA:
      secretKeyRef:
        key: ca.crt
        name: {{ template "kubeapps.fullname" $ }}-{{ .name }}
    {{- end }}
    {{- if .authorizationHeader }}
    header:
      secretKeyRef:
        key: authorizationHeader
        name: {{ template "kubeapps.fullname" $ }}-{{ .name }}
    {{- end }}
  {{- end }}
---
{{ end -}}
