{{- range .Values.apprepository.initialRepos }}
{{- if .caCert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-ca
  labels:
    app: {{ template "kubeapps.apprepository.fullname" $ }}
    chart: {{ template "kubeapps.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
  ca.crt: |-
{{- .caCert | b64enc | nindent 4 }}
---
{{- end }}
{{ end -}}
