{{- range .Values.apprepository.initialRepos }}
{{- if or .caCert .authorizationHeader }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kubeapps.fullname" $ }}-{{ .name }}
  labels:
    app: {{ template "kubeapps.name" $ }}
    chart: {{ template "kubeapps.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
{{- if .caCert }}
  ca.crt: |-
{{- .caCert | b64enc | nindent 4 }}
{{- end }}
{{- if .authorizationHeader }}
  authorizationHeader: |-
{{- .authorizationHeader | b64enc | nindent 4 }}
{{- end }}
---
{{- end }}
{{ end -}}